### ISSUE TITLE
Support for Spark, TensorFlow

### ISSUE THREAD

**Issue by vuolleko** [elfi-dev/elfi#104]
#### Summary:
Investigate possibility to use Spark and/or TensorFlow.

**Comment by datnamer** [comment]
Related: Integration with edward https://github.com/blei-lab/edward

@dustinvtran

**Comment by vuolleko** [comment]
As of 0.5 ELFI has a new scheduling system, which should facilitate adopting different frameworks.

**Comment by vuolleko** [comment]
Closing for now
