### ISSUE TITLE
Please explain how "schedule" works with SMC ABC

### ISSUE THREAD

**Issue by rostar** [elfi-dev/elfi#254]
#### Summary:
Please provide more detail on how the SMC ABC sampling works; in particular how the "schedule" affects sampling and performance.

#### Description:
The tutorial is quite brief on the SMC ABC sampling:

For sampling, one has to define the number of output samples, the number of populations and a schedule i.e. a list of quantiles to use for each population. In essence, a population is just refined rejection sampling.

N = 1000
schedule = [0.7, 0.2, 0.05]
%time result_smc = smc.sample(N, schedule)

Does that mean each population is a new prior for a rejection sampling round with the given quantile?

I would expect the performance of such an algorithm to be comparable to rejection sampling with quantile = 0.7*0.2*0.05 but the time it takes to sample for SMC ABC is much longer.

Thank you for any explanation or link!

Also, a progress bar similar to PyMC sampling would be very much appreciated.

**Comment by vuolleko** [comment]
Hi,

Thanks for pointing out an error in the documentation! In our current implementation, the `schedule` is not a list of quantiles, but a list of thresholds. I hope this explains your experience better.

In SMC-ABC, a population (+ noise) does indeed act as a prior distribution for the next population. Please see e.g. [Lintusaari et al., 2016](http://sysbio.oxfordjournals.org/content/early/2016/09/07/sysbio.syw077.full.pdf) for an explanation of the algorithm.

A progress bar or some kind of counter is planned.

**Comment by rostar** [comment]
Thank you!
Is there a way to define a schedule of quantiles? There are obvious difficulties with specifying thresholds for some problems.

**Comment by vuolleko** [comment]
At the moment, no. You can run rejection sampling for a while with a given (typically unusually large) quantile to get an idea of a good threshold for the first population, and then decrease it more and more for the next populations.
