### ISSUE TITLE
An elfi.Sample fails to get summary 

### ISSUE THREAD

**Issue by JohannGoethe** [elfi-dev/elfi#260]
#### Summary:
Please provide a short couple sentence summary.
I followed the tutorial, then
I got an elfi.Sample which fails to get summary.
While these is also error about parameters 

#### Description:
Describe the issue as clearly as possible.

TypeError: unsupported format string passed to numpy.ndarray.__format__
The prior distribution of parameter beta is [0.05,0.2], while in most results, result.sample_means['beta'] is 'inf'

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

import time
import numpy as np
import scipy.stats
import matplotlib
import matplotlib.pyplot as plt
import logging
logging.basicConfig(level=logging.INFO)
import elfi

MSE1 = []
MSE2 = []
seed=3333
tao = 0.198

def M(alpha, beta, batch_size=1, random_state=None):
    y = [1]
    alpha = np.float(alpha)
    beta = np.float(beta)
    theta = [alpha, alpha*beta, tao]
    theta = theta/np.sum(theta)
    i = 1 
    while i < 20:
        if y == []:
            break
        else:
            b = np.random.multinomial(1, theta, size=1)
            i = i + 1
            if b[0][2] == 1:
                y = y + [1]
            elif b[0][0] == 1:
                q = y/np.sum(y)
                p = q.tolist()
                a = np.random.multinomial(1, p, size=1).tolist()[0]
                y = [f+g for f,g in zip(y,a)]
            else:
                i = i - 2
                q = y/np.sum(y)
                p = q.tolist()
                a = np.random.multinomial(1, p, size=1).tolist()[0]
                y = [f-g for f,g in zip(y,a)]
                while 0 in y:
                    y.remove(0)
        yalpha = sorted(y)
    return yalpha

for seed in range(1000):
    elfi.new_model()     
    np.random.seed(seed+100500)
    
 
     
    alpha = elfi.Prior(scipy.stats.uniform, 0.05, 2, size=1)
    beta = elfi.Prior(scipy.stats.uniform, 0.05, 0.2, size=1)
    
    
    alpha0 = np.random.uniform(0.05,2,size=1).tolist()[0]
    beta0 = np.random.uniform(0.05,0.2,size=1).tolist()[0]
    y0 = M(alpha0, beta0)
       
    Y = elfi.Simulator(M, alpha, beta, observed=y0)
     
    def S1(x):
        t1 = len(x)/20
        return t1
    
    def S(x):
        y = 0
        for u in x:
            y = 100*y + u
        return y
    
    Su = elfi.Summary(S, Y)    
     
    d = elfi.Distance('euclidean', Su)
    
    rej = elfi.Rejection(d, batch_size=1, seed=seed) 
     
    result = rej.sample(n_samples=10, threshold=0)
    
    
    MSE1 = MSE1 + [np.square(result.sample_means['alpha'] - alpha0)]
    MSE2 = MSE2 + [np.square(result.sample_means['beta'] - beta0)]
end = time.time()
end-start
np.mean(MSE1)
np.mean(MSE2)

#### Current Output:
The current output. Knowing what is the current behavior is useful.

output of np.mean(MSE2) is inf
and even without loop, result.summary gets error:
TypeError: unsupported format string passed to numpy.ndarray.__format__

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

**Comment by vuolleko** [comment]
Hi. Since I don't know what you're trying to do, it's difficult to tell specific instructions. Some notes: 

I suggest first trying to get it to work without the for loop. 

The way you've defined your summary is very likely to give huge distances (possibly infinite).

Setting `threshold=0` with an euclidean distance means that all samples will be accepted. However, it could be a valid threshold for some other distance function, and so it should work... but it doesn't. Thanks for reporting this, I will investigate the bug. In your case, however, just set the threshold to some meaningful value.

**Comment by vuolleko** [comment]
Again, thanks for reporting this. Using `threshold=0` is now fixed in the `dev` branch. If you're not using that version, you can for now just set the threshold to some small value.

**Comment by JohannGoethe** [comment]
Thanks for the answer which is very helpful. I changed the summary statistics, now beta is not inf any longer, and also the threshold. Yes, I meant to get exact matches.
However, without the loop, I also can't get Sample.summary(), the same type of error as before. 
A notice: the function M is about disease transmission process with transmission rate alpha mutation rate gamma and recovery rate beta. I wrote a code before when M is only function of alpha, and other code is almost same as this, while Sample. summary() works.

**Comment by vuolleko** [comment]
You have given an argument `size=1` to the priors. Removing those should fix the dimensions.

**Comment by vuolleko** [comment]
Assuming `batch_size=1` as you have, the shapes from the priors are different:

`alpha = elfi.Prior(scipy.stats.uniform, 0.05, 2, size=1)` gives shape (1,1)
`alpha = elfi.Prior(scipy.stats.uniform, 0.05, 2)` gives shape (1,)

As a result, the averaging done by `result.sample_means` is an array (of len 1) for the former, a scalar for the latter. And the `summary` method does not work for arrays, at least for now, as this is just a convenience method and we can't prepare for everything (though a nicer error message would be in order). In any case, ELFI takes care of proper sizing with the single `batch_size` argument to `elfi.Rejection`, and you need not worry about it elsewhere. :)
