### ISSUE TITLE
About multiprocessing parallel, is there anything wrong?

### ISSUE THREAD

**Issue by JohannGoethe** [elfi-dev/elfi#266]
#### Summary:
Please provide a short couple sentence summary.

About multiprocessing parallel, is there anything wrong?

#### Description:
Describe the issue as clearly as possible.

Doing it once, it saves time, but in a for loop, it takes more time.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

import time

import numpy as np
import scipy.stats
import matplotlib
import matplotlib.pyplot as plt
import logging
logging.basicConfig(level=logging.INFO)

import elfi

MSE = []
MSE1 = []
t1=0
t=0

seed=55889

for seed in range(100):
    np.random.seed(seed+4543)
    elfi.new_model()
       
    alpha = elfi.Prior(scipy.stats.uniform, 0.05, 1)
    tao = 0.198
    
    def M(alpha, batch_size=1, random_state=None):
        y = [1]    
        for i in range(19):
            b = np.random.binomial(1, alpha/(alpha+tao), size=1)
            if b == 0:
                y = y + [1]
            else:
                q = y/np.sum(y)
                p = q.tolist()
                a = np.random.multinomial(1, p, size=1).tolist()[0]
                y = [f+g for f,g in zip(y,a)]
        yalpha = sorted(y)
        return yalpha
    
    theta = np.random.uniform(0.05,1,size=1)
    y0 = M(theta)
       
    Y = elfi.Simulator(M,alpha,observed=y0)
    Y1 = elfi.Simulator(M, alpha, observed=y0)
    
    def S(x):
        sum=np.sum([y*y for y in x])
        return sum
    
    Su = elfi.Summary(S, Y)
 
    def S1(x):
        t1 = len(x)/20
        return t1
    
    def S2(x):
        q = x/np.sum(x)
        p = q.tolist()
        t2 = 1 - np.sum([a*a for a in p])
        return t2
    
    Su1 = elfi.Summary(S1, Y1)

    d = elfi.Distance('euclidean', Su,Su1)
    d1 = elfi.Distance('euclidean', Su1)
    
    rej = elfi.Rejection(d, batch_size=1, seed=seed)                             
    rej1 = elfi.Rejection(d1, batch_size=1, seed=seed)
    start=time.time()
    **elfi.set_client('multiprocessing')**
    result = rej.sample(n_samples=100, threshold=0.01)
    end=time.time()
    t=end-start+t
    start1=time.time()
    **elfi.set_client('multiprocessing')**
    result1 = rej1.sample(n_samples=100, threshold=0.01)
    end1=time.time()
    t1=end1-start1+t1
    
    a1 = result1.samples_array
    b1 = np.sqrt(np.mean(np.square(a1-theta)))
    a = result.samples_array
    b = np.sqrt(np.mean(np.square(a-theta)))
    
    MSE = MSE + [b]
    MSE1 = MSE1 + [b1]

#### Current Output:
The current output. Knowing what is the current behavior is useful.

it has taken more than 3 hours, but without multiprocessing, around 3 hours

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

should be half the time, cauz when I run once, it takes about 2 minutes with parallel and 1 minute with multiprocessing.

**Comment by vuolleko** [comment]
Hi, a couple of things to note:
- you have to set the client before setting up Rejection to ensure it's used
- basic usage of the multiprocessing module does not in general guarantee faster completion, since your operating system may prioritize other processes and ELFI has to wait for their completion

**Comment by JohannGoethe** [comment]
Thanks a lot!

**Comment by JohannGoethe** [comment]
I have some further questions.

I run the code without loop, 
only  
%time result1 = rej1.sample(n_samples=100, threshold=0.01)
it should be few seconds without multiprocessing, but it has already half an hour when I use it.....
So I dare not run it on helix.....
If I want to use multiple cores on helix, is multiprocessing better or ipyprallel?
Because when I submit a code with the line like
! ipcluster -4 daemon...in the tutorial
I got an error..

Thank you so much

**Comment by vuolleko** [comment]
I tested your case and it only takes a minute or so on my computer with or without multiprocessing. Have you observed a system resource monitor or something to indicate the level of memory and CPU usage?

If you run the inference on a single computer, there should be no difference whether you use multiprocessing or ipyparallel. In more complex computing environments you cannot use multiprocessing. Note that you don't have to assign all your cores to ELFI so that your operating system can still work properly.

What error did you get with ipyparallel? The procedure may be a bit different in Windows.

**Comment by JohannGoethe** [comment]
thank you so much.
In my computer the CPU varies quickly, python occupies vary from 90 percent to 6 percent and extremely slow, without multiprocessing maybe seconds but already like ten minutes.

when I run ipyparallel on helix, I got "File "transmission2.py", line 97
    !ipcluster start -n 4 --daemon
    ^
SyntaxError: invalid syntax
"

**Comment by JohannGoethe** [comment]
other codes are the same except I change multiprocessing to ipyparallel as the tutorial indicate

**Comment by vuolleko** [comment]
If the CPU usage by Python varies, is some other process consuming more?

I don't have a Windows computer to test this now, but try giving the command `ipcluster start -n 4` in a terminal window. If the command is not found, you may have to give the full path to the `ipcluster` script.

**Comment by vuolleko** [comment]
I assume this was resolved. Closing.
