### ISSUE TITLE
quickstart page: two oddities

### ISSUE THREAD

**Issue by umbertopicchini** [elfi-dev/elfi#295]
#### Summary:
the quickstart page lacks an "import elfi". Also, for clarity, priors should be defined at a latter stage 

#### Description:
Describe the issue as clearly as possible.

I am totally new to Python, and when I say "new" I mean that I have installed it for the first time today (via Anaconda). So what follows might be silly and/or totally obvious to others, as of course some python knowledge is required to play with ELFI. But anyway, I managed to go through the quickstart https://elfi.readthedocs.io/en/latest/quickstart.html#

However, this was not pain-free, hence here are my suggestions:

- please add an "import elfi" right at the top. This is completely missing and for a Python novice it will be painful to try to find the reason for those "NameError: name 'elfi' is not defined".
- again in th quickstart page: it is a strange workflow to define the priors before everything else. I find this to be totally non-intuitive. My suggestion is to place the priors definition after the data (y0) have been generated.

**Comment by hpesonen** [comment]
Thanks for pointing this out! elfi.readthedocs.io have been automatically generated from the Jupyter notebooks, e.g. quickstart-quide https://github.com/elfi-dev/notebooks/blob/master/quickstart.ipynb where `import elfi` can be found. For some reason this is missing from the webpage. We will look into this. 

About the workflow: I believe it's been described to follow the structure of the DAGs. It's true, that from natural modelling perspective we'd define simulator and generate data, after which we'd define priors for the simulator parameters that would make sense. Feedback is appreciated!
