### ISSUE TITLE
sampling times in bolfi.sample

### ISSUE THREAD

**Issue by umbertopicchini** [elfi-dev/elfi#297]
#### Summary:

Wall time in bolfi.sample seems to depend on the n_evidence parameter in bolfi.fit while I think this should not be the case.

#### Description:
The advantage in using a surrogate of the discrepancies fitted using Gaussian processes, is that, once the GP hyperparameters are determined, MCMC sampling (via bolfi.sample) should be completely independent of the model simulator, thus resulting in a scalable algorithm.
If I have not misunderstood the theory in the relevant paper, once bolfi.fit(n_evidence=xxx) has completed, the execution of bolfi.sample(numsamples) to produce numsaples posterior samples should require the same wall-clock time, no matter the value I set for n_evidence. This is because bolfi.samples only invokes the fitted GP and never the true model simulator.

This is clearly not the case, hence I wonder what I am missing.

#### Reproducible Steps:
I build up on the example in https://elfi.readthedocs.io/en/latest/usage/BOLFI.html

I run all the code before the call to elfi. BOLFI. Then I run the following:

bolfi = elfi.BOLFI(log_d, batch_size=1, initial_evidence=20, update_interval=10, bounds={'t1':(-2, 2), 't2':(-1, 1)}, acq_noise_var=[0.1, 0.1], seed=seed)

Then I fit the GP model on 100  evidence points:
%time post = bolfi.fit(n_evidence=100)
INFO:elfi.methods.posteriors:Using optimized minimum value (-1.6966) of the GP discrepancy mean function as a threshold
Wall time: 24.7 s

and produce 1000 posterior samples
%time result_BOLFI = bolfi.sample(1000, info_freq=1000)
4 chains of 1000 iterations acquired. Effective sample size and Rhat for each parameter:
t1 2063.7620137995186 1.0014860681196993
t2 2415.9426764728387 0.9994192510776999
Wall time: **57.4 s**

Now I enlarge the number of evidence points to 300:
%time post = bolfi.fit(n_evidence=300)
INFO:elfi.methods.posteriors:Using optimized minimum value (-1.6316) of the GP discrepancy mean function as a threshold
Wall time: 1min 4s

and sample 1000 draws:

%time result_BOLFI = bolfi.sample(1000, info_freq=1000)
4 chains of 1000 iterations acquired. Effective sample size and Rhat for each parameter:
t1 1908.9201493103064 1.0000733568191036
t2 2329.652810214964 1.0009504568577294
Wall time: **1min 35s**

#### Expected Output:
So posterior sampling time has increased from 57" to 1'35" in the two attempts. Shouldn't the sampling times be roughly the same?

#### ELFI Version:
0.7.3
#### Python Version:
3.5.6
#### Operating System:
Windows 10

**Comment by umbertopicchini** [comment]
oh great, makes sense! I forgot about the NUTS peculiarities....
Thank you!

**Comment by umbertopicchini** [comment]
Is NUTS the only available sampler within bolfi.sample? How do I find the list of parameters/options for bolfi.sample in the documentation?

**Comment by vuolleko** [comment]
There's an open PR #296 to add the existing Metropolis sampler to the `BOLFI.sample` interface, but for the time being, NUTS is your only built-in option. Basically you could of course give the BOLFI posterior logpdf to any external sampler.

The standard Python docstring shows the available arguments for `BOLFI.sample`, available also here:

https://elfi.readthedocs.io/en/latest/api.html#elfi.BOLFI.sample
