### ISSUE TITLE
Convert n_sim and n_samples in 'float' to 'int' automatically

### ISSUE THREAD

**Issue by alexaushev** [elfi-dev/elfi#310]
#### Summary:
If n_sim and n_samples (e.g. elfi.Rejection.set_objective()) are type 'float', the code gives "TypeError".

#### Description:
When n_sim and n_samples (e.g. elfi.Rejection.set_objective()) are provided in the format '10e7', self.objective['n_samples'] becomes 'float', which gives "TypeError: 'float' object cannot be interpreted as an integer" in parameter_inference.py::_init_samples_lazy  line  "samples[node] = np.ones(shape, dtype=dtype) * np.inf". In my opinion, the format '10e7' is more convenient than 10000000 when dealing with large numbers. This can be solved by converting the variables to 'int' automatically.

#### Reproducible Steps:
The problem can be reproduced with any simulator:
    n_sim = 10e3
    n_samples = 10e2
    rej = elfi.Rejection(m, 'dist')
    rej.set_objective(n_samples=n_samples, n_sim=n_sim)

**Comment by hpesonen** [comment]
Hi, 
the behaviour is as expected as `n_samples` and `n_sim` are requested as type `int`. However, numbers with scientific notation would sometimes be convenient and this could be implemented as a feature in the future. 

p.s. note that 10e7 != 10000000 == 1e7
