### ISSUE TITLE
threshold value returned when specifying 'n_sim' in Rejection sampler

### ISSUE THREAD

**Issue by vaseline555** [elfi-dev/elfi#321]
Problem Statement)
Hello, I have a simple question in understanding of setting a threshold value when I only pass 'n_sim' and 'n_samples' arguments to the rejection sampler.

When inspecting the source code of Rejection class in elfi.methods.parameter_inference code,
there exists a explanation of determining a threshold value when 'n_sim' is passed:
(https://elfi.readthedocs.io/en/latest/_modules/elfi/methods/parameter_inference.html#Rejection.set_objective)

`n_sim : int
Total number of simulations. The threshold will be the n_samples **smallest** discrepancy among n_sim simulations.`

Why the threshold is set to **smallest** discrepancy among n_samples (i.e. accepted samples)?

I think it is reasonable to set a threshold value to be the largest discrepancy value among collected n_samples in n_sim simulations.

For example, when I set n_samples = 10, n_sim=10000,
finished rejection sampling,
sorted discrepancy values of 1000 simulated samples in an increasing order.

As a result, I got the sequence of discrepancy values:
1, 1.2, 1.4, 4, 4.3, 5, 7, 8, 9, 10, 11, 12, 13, ... , 10000.

Then, shouldn't the threshold value be 10? not 1?
Did I make a mistake in understanding the implementation?
(Reasoning: in Biau et al. 2013, (https://arxiv.org/pdf/1207.6461.pdf)
we can infer the fact that a threshold value is at least smaller than or equal to an infimum of a discrepancy of rejected samples)

Question)
* 1-1
If my understanding is correct, is there any reference on such an implementation?
* 1-2
In what part of a code should I change when I want the returned threshold value to be the largest discrepancy value among n_samples?

* 2
If wrong, what is the returned threshold value in my example?
Is it 10?
Thank you!

**Comment by hpesonen** [comment]
Hi, in your example, the value that would be returned is 10. The doc should be read as "The threshold will be the Nth **smallest** discrepancy among n_sim simulations" and in this case N == `n_samples`. Hope this helps!
