### ISSUE TITLE
Can rejection sampling be done with no explicit passing of observed data to a simulator?

### ISSUE THREAD

**Issue by vaseline555** [elfi-dev/elfi#323]
For example,
in ELFI tutorial...
We should specify observed data like below:

`Y = elfi.Simulator(MA2, t1, t2, observed=y_obs)`

for calculating a discrepancy like:

`d = elfi.Distance('euclidean', S1, S2)`

What I wonder is,
without explicitly passing 'observed' argument to the Simulator object,
can we make it possible to do ABC-rejection by modifying discrepancy function?
e.g. instead of passing observed data to Simulator,
calculate all discrepancies between simulated samples and observed samples in a custom Distance function.

**Comment by kskyten** [comment]
Could you give an example of what you are trying to achieve? Do you mean to calculate your custom discrepancy without summarizing the data first? The `Simulator` node is analogous to a likelihood function in a traditional statistical model. The notation
`Y = elfi.Simulator(MA2, t1, t2, observed=y_obs)` means that we believe that the observed data could have come from the simulator given suitable parameters. These unknown parameters are the goal of our inference.

**Comment by hpesonen** [comment]
Closing this as there has not been any activity since Feb 2020.
