### ISSUE TITLE
Regression adjustment returns point estimate in specific case

### ISSUE THREAD

**Issue by joshhjacobson** [elfi-dev/elfi#325]
Hi,

This issues arises from a non-standard implementation of the rejection sampler. The summary statistics I'm working with are a set of distribution quantiles; instead of simulating random samples and computing the quantiles of these samples, I've found it's much faster to directly calculate the theoretical quantiles from a given parameter set in the "simulation" step, then define dummy summary nodes which simply pick out the elements of the simulation output. However, when I apply the regression adjustment via `elfi.adjust_posterior()`, the posterior distribution of each parameter becomes a point estimate (i.e. the `outputs` arrays contain the same value repeated `n_samples` times).

In the example below, I attempt to model the quantiles of a chi-squared distribution with 5 degrees of freedom using the normal distribution:
```python 
import numpy as np
import scipy.stats
import elfi

seed = 20200227

# Observed data
df = 5
qtiles = np.arange(0.1, 1, 0.1)
quantiles = scipy.stats.chi2.ppf(qtiles, df)

# Simulation function
def theoretical_quantiles(q_vec, loc, scale, batch_size=1, random_state=None):
        loc, scale = np.atleast_1d(loc, scale)
        return scipy.stats.norm.ppf(q_vec, loc[:, None], scale[:, None])

# Summary function
def match_quantile(q, idx):
    return np.atleast_2d(q)[:, idx]

# Model object
mod = elfi.new_model()

# Priors
elfi.Prior(scipy.stats.norm, quantiles.mean(), quantiles.std(), model=mod, name='loc')
elfi.Prior(scipy.stats.uniform, 0, 10, model=mod, name='scale')

# Simulation node
s = elfi.Simulator(theoretical_quantiles, qtiles, mod['loc'], mod['scale'], 
               observed=quantiles, name='norm')

# Dummy summary statistic nodes 
summary_stats = list()
for idx in range(len(qtiles)):
    summary_stats.append(elfi.Summary(match_quantile, mod['norm'], idx, name=f"S{idx}"))

# Distance metric
d = elfi.Distance('euclidean', *summary_stats, name='d')

# Rejection sampling
rejection_sampler = elfi.Rejection(mod, 'd', 
                         output_names=[ss.name for ss in summary_stats], 
                         batch_size=1000, seed=seed)

res = rejection_sampler.sample(500, quantile=0.05)
adj = elfi.adjust_posterior(model=mod, sample=res, summary_names=[ss.name for ss in summary_stats])

res.plot_pairs()
adj.plot_pairs()
adj.outputs
```

In `adj.outputs` you should see an array of length `n_samples` for each distribution parameter (i.e. `loc` and `scale`), each containing only one unique value. 

I'm not sure whether this is actually an issue with the `elfi.adjust_posterior()` method or not. Interestingly, when my model is setup using a simulation function which actually generates a random sample and summary nodes which actually compute empirical quantiles of the sample, I do not see this behavior.

**Comment by hpesonen** [comment]
Hi! I think that linear regression adjustment actually works as intended for an observation model without noise, which essentially is a linear system of equations (L) in this case. The adjustment "corrects" all the samples as the same solution to (L).

**Comment by joshhjacobson** [comment]
What do you mean by "an observation model without noise"? Is this in reference to the original observed data (i.e. theoretical quantiles of the chi-squared in my example), or the lack of random simulation from the parameters in the rejection sampling stage?

**Comment by joshhjacobson** [comment]
I see what you mean. The system can be described as `$y = X\beta$` where $y$ is the vector of samples for a single parameter, $X$ is a matrix with samples over rows and summary statistics (selected quantiles in this case) over the columns, and $\beta$ is a vector of coefficients. When fitting this model manually using `sklearn.linear_model.LinearRegression().fit(X, y)`, I get an r-squared of 1, i.e. a perfect fit. As it turns out, the quantile function for the Normal distribution is a linear function of the location and scale parameters so the point estimate is actually the correct result. This is not an issue with ELFI at all, just my own understanding!
