### ISSUE TITLE
Comparison to other ABC software

### ISSUE THREAD

**Issue by kskyten** [elfi-dev/elfi#40]
What sets ELFI apart from other commonly used ABC software? We should decide what software we want to compare against and what features should be compared. Here are some ideas:
- How easy is it to formulate a inference problem? Is the problem limited to some specific domain (e.g. genetics)?
- Developer friendliness: How easy is it to develop new ABC methods?
- Can the ABC problem be inferred with different methods without changing the code?

**Comment by datnamer** [comment]
Can I provide my own black box for the model? ie an Agent Based Model

**Comment by akangasr** [comment]
@datnamer: sure, any generative model should work in principle

**Comment by kskyten** [comment]
I compared ELFI to the following general purpose ABC frameworks in my bachelor's thesis:

- abc
- EasyABC
- ABC-SysBio 
- ABCtoolbox 

The rest of the software on the wikipedia list seemed to be more specialized to specific applications. To summarize the advantages of ELFI:
- flexible modeling,
- separate representation of the inference problem
- inference model persistence
- grid computation
- efficient inference (i.e BOLFI).
- high dimensional ABC (see the Gaussian copula PR)
