### ISSUE TITLE
Combine vectorization wrappers

### ISSUE THREAD

**Issue by lintusj1** [elfi-dev/elfi#73]
All the vectorized wrappers for different nodes could be combined to one vectorized function. Currently they share a lot of code. 

How to do it:
For positional arguments take the i:th element from each. If it is a tuple (as in distance node, take the i:th element from each array in the tuple). `n_sim` would be always one. If `prng` (stochastic mixin) is given, pass it as a keyword argument to the operation function.

**Comment by vuolleko** [comment]
Supported as of 0.5.
