### ISSUE TITLE
Node.reset()

### ISSUE THREAD

**Issue by lintusj1** [elfi-dev/elfi#87]
When the DAG structure is changed, other nodes not part of the change need sometimes to be notified about it, so that they can e.g. reset their data. Currently this is achieved through `Node.reset`. However the implementation is non optimal at the moment and should be refactored.

**Comment by vuolleko** [comment]
I think this is solved in 0.5?

**Comment by lintusj1** [comment]
This is related to the old version. Not relevant any longer so closing this. At some point we might add the functionality that models and their nodes have a version number. This would be mainly useful for knowing if persisted data is still valid for the node.
